---
all:
  hosts:
    jenkins-master-01: 
      ansible_host: 158.160.100.50
    jenkins-agent-01:
      ansible_host: 158.160.116.201
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: glisikh
    ansible_ssh_private_key_file: "/.ssh/id_ed24532"