{
 "title": "homework",
 "time": { "from": "2023-11-19T13:24:03.430Z", "to": "2023-11-19T13:36:18.150Z" },
 "panels": [
  {
   "title": "утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job='nodeexporter',mode='idle'}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance='nodeexporter:9100', job='nodeexporter'})"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg by (instance)(node_load1)", "legendFormat": "node_load1" },
    { "expr": "avg by (instance)(node_load5)", "legendFormat": "node_load5" },
    { "expr": "avg by (instance)(node_load15)", "legendFormat": "node_load15" }
   ]
  },
  {
   "title": "количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device='/dev/mapper/ubuntu--vg-ubuntu--lv', fstype='ext4', instance='nodeexporter:9100', job='nodeexporter', mountpoint='/'}"
    }
   ]
  }
 ]
}