- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector
  tags:
    - vector

- name: Install and configuring lighthouse
  hosts: light
  roles:
    - lighthouse
  tags:
    - lighthouse