apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      multitool: back
  template:
    metadata:
      labels:
        multitool: back
    spec:
      containers:
      - name: back
        image: praqma/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - name: multitool
          containerPort: 8080
