apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    nginx: front
  ports:
  - name: front
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    multitool: back
  ports:
  - name: back
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
